[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "duplicate-question-pair"
version = "1.0.0"
description = "Duplicate Question Pair Detection"
requires-python = ">=3.9"

